appName: cocos-backend
env: prod
port: 3000
api:
  currency:
    market:
      ticker: ARS
  orders:
    schemas:
      types:
        - MARKET
        - LIMIT
      sides:
        cash:
          - CASH_IN
          - CASH_OUT
db:
  type: &dialect postgres
  auth:
    host:
    port:
    user:
    password:
    dataBase:
  config:
    dialect: *dialect
    logging: false
    pool:
      max: 3
      min: 1
      acquire: 30000
      idle: 10000
