appName: cocos-backend
env: qa
port: 3000
api:
db:
  type: &dialect postgres
  auth:
    host: 'raja.db.elephantsql.com'
    port: 5432
    user: 'zdklxogo'
    password: '13RIIZd_jhUkM5LsuWzWdRyPlFJsmnVj'
    dataBase: 'zdklxogo'
  config:
    dialect: *dialect
    logging: true
    pool:
      max: 3
      min: 1
      acquire: 30000
      idle: 10000
