appName: cocos-backend
env: qa
port: 3000
api:
  orders:
    schemas:
      types:
        - MARKET
        - LIMIT
      sides:
        cash:
          - CASH_IN
          - CASH_OUT
db:
  type: &dialect postgres
  auth:
    host:
    port:
    user:
    password:
    dataBase:
  config:
    dialect: *dialect
    logging: true
    pool:
      max: 3
      min: 1
      acquire: 30000
      idle: 10000
